services:
  - type: web
    name: team-boards
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn team_bords.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: team-boards.onrender.com
